export const talmudTractates = {
  Zeraim: [
    { id: 1, name: 'Berakhot' },
    { id: 2, name: 'Peah' },
    { id: 3, name: 'Demai' },
    { id: 4, name: 'Kilayim' },
    { id: 5, name: 'Sheviit' },
    { id: 6, name: 'Terumot' },
    { id: 7, name: 'Maaserot' },
    { id: 8, name: 'Maaser Sheni' },
    { id: 9, name: 'Challah' },
    { id: 10, name: 'Orlah' },
    { id: 11, name: 'Bikkurim' },
  ],
  Moed: [
    { id: 12, name: 'Shabbat' },
    { id: 13, name: 'Eruvin' },
    { id: 14, name: 'Pesachim' },
    { id: 15, name: 'Shekalim' },
    { id: 16, name: 'Yoma' },
    { id: 17, name: 'Sukkah' },
    { id: 18, name: 'Beitza' },
    { id: 19, name: 'Taanit' },
    { id: 20, name: 'Megillah' },
    { id: 21, name: 'Moed Katan' },
    { id: 22, name: 'Chagiga' },
  ],
  Nashim: [
    { id: 23, name: 'Yevamot' },
    { id: 24, name: 'Ketubot' },
    { id: 25, name: 'Nedarim' },
    { id: 26, name: 'Nazir' },
    { id: 27, name: 'Sotah' },
    { id: 28, name: 'Gittin' },
    { id: 29, name: 'Kiddushin' },
  ],
  Nezikin: [
    { id: 30, name: 'Baba Kamma' },
    { id: 31, name: 'Baba Batra' },
    { id: 32, name: 'Baba Metzia' },
    { id: 33, name: 'Sanhedrin' },
    { id: 34, name: 'Makkot' },
    { id: 35, name: 'Shevuot' },
    { id: 36, name: 'Eduyot' },
    { id: 37, name: 'Avodah Zarah' },
    { id: 38, name: 'Horayot' },
  ],
  Kodashim: [
    { id: 39, name: 'Zevachim' },
    { id: 40, name: 'Menachot' },
    { id: 41, name: 'Chullin' },
    { id: 42, name: 'Bekhorot' },
    { id: 43, name: 'Arakhin' },
    { id: 44, name: 'Temurah' },
    { id: 45, name: 'Keritot' },
    { id: 46, name: 'Meilah' },
    { id: 47, name: 'Kinnim' },
  ],
  Taharot: [
    { id: 48, name: 'Niddah' },
    { id: 49, name: 'Mikvaot' },
    { id: 50, name: 'Kelim' },
    { id: 51, name: 'Oholot' },
    { id: 52, name: 'Nega’im' },
    { id: 53, name: 'Parah' },
    { id: 54, name: 'Taharot' },
    { id: 55, name: 'Machshirin' },
    { id: 56, name: 'Zavim' },
    { id: 57, name: 'Yadayim' },
    { id: 58, name: 'Uktzin' },
  ],
};
